name: deploy-on-github-pages

on:
    push:
        branches:
            - main

jobs:
    deploy-on-github-pages:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Setup Node.js
              uses: actions/setup-node@v2
              with:
                  node-version: '16'

            - name: Install dependencies
              run: npm install -f

            - name: Build
              run: npm run build

            - name: Import GPG key
              uses: crazy-max/ghaction-import-gpg@v5
              with:
                  gpg_private_key: ${{ secrets.GPG_PRIVATE_KEY }}
                  passphrase: ${{ secrets.PASSPHRASE }}
                  git_user_signingkey: true
                  git_commit_gpgsign: true

            - name: Deploy
              if: success()
              uses: crazy-max/ghaction-github-pages@v3
              with:
                  committer: JayantGoel001 <jgoel92@gmail.com>
                  author: JayantGoel001 <jgoel92@gmail.com>
                  keep_history: true
                  build_dir: "./build"
                  jekyll: true
                  commit_message: "Auto-generated commit [ci skip]"
              env:
                  GITHUB_TOKEN: ${{ secrets.GHP_TOKEN }}
