name: publish-package
on:
    release:
        types: [created]
        branches:
            - main

jobs:
    publish-package-on-github-registry:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  registry-url: 'https://npm.pkg.github.com'
            - name: Install dependencies 🔧 and Publish package on NPM 📦
              run: |
                  npm install
                  npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GH_NPM_TOKEN }}

    publish-package-on-npm-registry:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2
            - name: Setup Node
              uses: actions/setup-node@v2
              with:
                  node-version: '16.x'
                  registry-url: 'https://registry.npmjs.org'
            - name: Install dependencies 🔧 and Publish package on NPM 📦
              run: |
                  npm install
                  npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
